name: munch_app
description: Munch Mobile App

version: 0.18.0+5

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Required
  http: ^0.12.0
  intl: ^0.15.7
  json_annotation: ^2.0.0

  # Platform Plugins
  geolocator: ^2.1.1
  url_launcher: ^4.0.2
  shared_preferences: ^0.4.3
  flutter_webview_plugin: ^0.3.0+2
  share: ^0.5.3
  flutter_local_notifications: ^0.4.3

  # Firebase & Authentication
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  flutter_facebook_login: ^1.1.1

  # Core Frameworks
  rxdart: ^0.20.0
  sqflite: ^0.13.0+1
  flutter_cache_store: ^0.3.1-RC2

  # Core Helpers
  cached_network_image: ^0.5.1
  latlong: ^0.6.1

  # Widgets
  flutter_spinkit: ^3.0.0
  flutter_staggered_grid_view: ^0.2.4
  shimmer: ^0.0.6
  flutter_range_slider: ^1.0.1
  google_maps_flutter: ^0.0.3+3

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
  - family:  MunchIcons
    fonts:
    - asset: fonts/MunchIcons.ttf

  assets:
  - assets/img/