name: munch_app
description: Munch Mobile App

version: 0.21.0+41

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Required
  http: ^0.12.0+1
  intl: ^0.15.7
  json_annotation: ^2.0.0

  # Platform Plugins
  geolocator: ^3.0.1
  url_launcher: ^5.0.1
  shared_preferences: ^0.5.1+1
  flutter_webview_plugin: ^0.3.0+2
  share: ^0.6.0+1
  flutter_local_notifications: ^0.5.2

  # Firebase & Authentication
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+4
  firebase_analytics: ^2.0.2+1
  flutter_facebook_login: ^2.0.0

  # Core Frameworks
  rxdart: ^0.21.0
  sqflite: ^1.1.0

  # Core Helpers
  cached_network_image: ^0.6.2
  latlong: ^0.6.1

  # Widgets
  flutter_spinkit: "^3.1.0"
  flutter_staggered_grid_view: ^0.2.7
  shimmer: ^1.0.0
  flutter_range_slider: ^1.1.0
  google_maps_flutter: ^0.3.0+2
  pin_code_view: 0.1.1

dev_dependencies:
  build_runner: ^1.0.0
  # flutter packages pub run build_runner build
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family:  MunchIcons
      fonts:
        - asset: fonts/MunchIcons.ttf

  assets:
    - assets/img/