name: munch_app
description: Munch Mobile App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # Required
  http: ^0.12.0
  intl: ^0.15.7
  json_annotation: ^2.0.0

  # Platform Plugins
  url_launcher: ^4.0.2
  shared_preferences: ^0.4.3
  flutter_webview_plugin: ^0.3.0+2

  # Firebase & Authentication
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  flutter_facebook_login: ^1.1.1

  # Core Frameworks
  rxdart: ^0.20.0
  sqflite: ^0.12.2+1

  # Core Helpers
  cached_network_image: ^0.6.0-alpha.2

  # Widgets
  flutter_spinkit: ^3.0.0
  flutter_staggered_grid_view: ^0.2.4
  flutter_platform_widgets: ^0.5.0
  shimmer: ^0.0.6

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  - family:  MunchIcons
    fonts:
    - asset: fonts/MunchIcons.ttf

  assets:
  - assets/img/