/// Flutter icons MunchIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MunchIcons
///      fonts:
///       - asset: fonts/MunchIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MunchIcons {
  MunchIcons._();

  static const _kFontFam = 'MunchIcons';

  static const IconData logo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData navigation_back = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData navigation_cancel = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData navigation_caret_down = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData navigation_setting = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData onboarding_facebook = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData rip_heart_filled = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData rip_heart = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData rip_toast_cancel = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData rip_toast_check = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData rip_toast_heart = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData search_header_filter = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData search_header_back = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData search_header_reset = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData search_header_search = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData tabbar_discover = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData tabbar_feed = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData tabbar_profile = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData tastebud_places = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData tastebud_preferences = const IconData(0xe813, fontFamily: _kFontFam);
}
