/// Flutter icons MunchIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MunchIcons
///      fonts:
///       - asset: fonts/MunchIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MunchIcons {
  MunchIcons._();

  static const _kFontFam = 'MunchIcons';

  static const IconData filter_anywhere = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData filter_between = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData filter_cancel = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData filter_nearby = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData filter_search = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData filter_timing = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData map_direction = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData map_fold = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData map_landmark = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData map_place = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData map_train = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData navigation_back = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData navigation_cancel = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData navigation_caret_down = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData navigation_setting = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData navigation_more = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData onboarding_facebook = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData rip_edit = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData rip_expand = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData rip_gallery = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData rip_heart_filled = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData rip_heart = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData rip_toast_cancel = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData rip_toast_heart = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData rip_toast_check = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData search_card_home_dtje_info = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData search_card_home_dtje_pan = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData search_header_back = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData search_header_filter = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData search_header_reset = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData search_header_search = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData suggest_anywhere = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData suggest_nearby = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData suggest_place = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData suggest_pointer = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData suggest_recent = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData tabbar_discover = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData tabbar_feed = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData tastebud_places = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData tabbar_profile = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData tastebud_preferences = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData location_home = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData location_cancel = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData location_recent = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData location_work = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData location_nearby = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData location_pin = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData location_bookmark_filled = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData location_bookmark = const IconData(0xe832, fontFamily: _kFontFam);
}
